on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Demo CI on ECR

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      #- name: Install AWS CLI
      #  run: |
 #         curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
     #     unzip awscliv2.zip
      #    sudo ./aws/install

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region ${{ secrets.AWS_ECR_REGION }} | docker login --username AWS --password-stdin public.ecr.aws

      # 아래는 시크릿 리포지토리용
      #- name: Login to Amazon ECR
      #  id: login-ecr
      #  uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: public.ecr.aws
          ECR_REPOSITORY: ${{ secrets.ECR_PUB_REPO }}
          IMAGE_TAG: ${{ github. sha }}
        run: |
          # Build a docker container and push it to ECR
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Cleanup old images
        run: |
          images=$(aws ecr-public describe-images --repository-name ${{ secrets.ECR_PUB_REPO_NAME }} --region ${{ secrets.AWS_ECR_REGION }} --output json | jq -r '.imageDetails | sort_by(.imagePushedAt) | .[:-2] | .[].imageDigest')
          if [ -z "$images" ]; then
            echo "No images found for deletion."
          else
            echo "Images to be deleted: $images"
            for image in $images; do
              aws ecr-public batch-delete-image --repository-name ${{ secrets.ECR_PUB_REPO_NAME }} --image-ids imageDigest=$image --region ${{ secrets.AWS_ECR_REGION }}
            done
          fi


